# Root Route

GET http://localhost:3000/

###
# User Routes
###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/auth

###

POST  http://localhost:3000/api/users
Content-Type: application/json

{
	"email": "some2@some.com",
	"password": "some123"
}

###
GET http://localhost:3000/api/hodling
Content-Type: application/json

{
  "uid": "620a796f5829dab41f6ed7c1"
}

###
GET http://localhost:3000/api/pllist

{
  "uid": "620a796f5829dab41f6ed7c1"
}

###
POST http://localhost:3000/api/hodling
Content-Type: application/json

{
  "coin": "shib",
  "pair": "inr",
  "qty": 10,
  "price": 4,
  "term": "short",
  "uid": "620a3530de00e6281d3c51da"
}

###
POST http://localhost:3000/api/pllist
Content-Type: application/json

{
  "uid": "620a796f5829dab41f6ed7c1",
  "coin": "shib",
  "pair": "inr",
  "qty": 165837,
  "buyPrice": 0.00003015,
  "soldPrice": 0.00003184,
  "term": "short"
}

###
GET http://localhost:3000/api/auth
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjIwMjgxZTcyNTg3MTJkY2U3NDU0NTE5In0sImlhdCI6MTY0NDQ5NDc5NywiZXhwIjoxNjQ0ODU0Nzk3fQ.yU__Jagc6hmNhBNn4NM0TWOq1u-qj_9EURVeNPnso4w

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
	"email": "some2@some.com",
	"password": "some123"
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
	"email": "some2@some.com",
	"password": "some123!"
}


###
POST http://localhost:3000/api/hodling/update
Content-Type: application/json

{
  "coinOld": "usdt",
  "coin": "brc"
}

###

GET http://localhost:3000/api/hodling

###
POST http://localhost:3000/api/hodling/delete
Content-Type: application/json

{
  "coin": "usdt",
  "pair": "inr",
  "qty": "58935"
}

###
GET http://localhost:3000/signin

###
GET http://localhost:3000/api/allOrders

###
GET http://localhost:3000/api/funds

{
  "uid": "620a3530de00e6281d3c51da"
}

###
GET http://localhost:3000/api/keys

{
  "uid": "620a3530de00e6281d3c51da"
}

###

POST http://localhost:3000/api/keys
Content-Type: application/json

{
  "uid": "620a3530de00e6281d3c51da",
  "api": "somekey",
  "sec": "somesecret"
}
