# Root Route

GET http://localhost:3000/

###
# User Routes
###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/auth

###

POST  http://localhost:3000/api/users
Content-Type: application/json

{
	"name": "some2",
	"email": "some2@some.com",
	"password": "some123"
}

###
GET http://localhost:3000/api/hodling

###
GET http://localhost:3000/api/pllist

###
POST http://localhost:3000/api/hodling
Content-Type: application/json

{
  "coin": "usdt",
  "pair": "inr",
  "qty": 0.027273,
  "price": 78.56,
  "term": "short"
}

###
POST http://localhost:3000/api/pllist
Content-Type: application/json

{
  "coin": "shib",
  "pair": "usdt",
  "qty": 165837,
  "buyPrice": 0.00003015,
  "soldPrice": 0.00003184,
  "term": "short"
}

###

GET http://localhost:3000/api/auth
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFmMTFjNzc5OTJlNjFkOTcwN2NkNjFkIn0sImlhdCI6MTY0MzE5MTQxNSwiZXhwIjoxNjQzNTUxNDE1fQ.LoZc6vFaOTW1aHBR1CcTYf9SypfJwTiKdjdzZ_v6n1s

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
	"email": "some2@some.com",
	"password": "some123"
}


###
POST http://localhost:3000/api/hodling/update
Content-Type: application/json

{
  "coinOld": "usdt",
  "coin": "brc"
}

###

GET http://localhost:3000/api/hodling

###
POST http://localhost:3000/api/hodling/delete
Content-Type: application/json
{
  "coinOld": "brc"
}

###
GET http://localhost:3000/api/allOrders